nugetgallery/Website/Entities/Package.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NuGetGallery
{
    [DisplayColumn("Title")]
    public class Package : IEntity
    {
        public Package()
        {
            Authors = new HashSet<PackageAuthor>();
            Dependencies = new HashSet<PackageDependency>();
            SupportedFrameworks = new HashSet<PackageFramework>();
            Listed = true;
        }

        public int Key { get; set; }

        public PackageRegistration PackageRegistration { get; set; }
        public int PackageRegistrationKey { get; set; }

        public virtual ICollection<PackageStatistics> DownloadStatistics { get; set; }
        public virtual ICollection<PackageAuthor> Authors { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string Copyright { get; set; }
        public DateTime Created { get; set; }
        public virtual ICollection<PackageDependency> Dependencies { get; set; }
        
        /// <remarks>
        /// Has a max length of 4000. Is not indexed but *IS* used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string Description { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string ReleaseNotes { get; set; }
        public int DownloadCount { get; set; }
        
        /// <remarks>
        /// Is not a property that we support. Maintained for legacy reasons.
        /// </remarks>
        public string ExternalPackageUrl { get; set; }

        [StringLength(10)]
        public string HashAlgorithm { get; set; }

        [StringLength(256), Required]
        public string Hash { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string IconUrl { get; set; }
        public bool IsLatest { get; set; }
        public bool IsLatestStable { get; set; }
        public DateTime LastUpdated { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string LicenseUrl { get; set; }

        [StringLength(20)]
        public string Language { get; set; }

        public DateTime Published { get; set; }
        public long PackageFileSize { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string ProjectUrl { get; set; }
        public bool RequiresLicenseAcceptance { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and not used for searches. Db column is nvarchar(max).
        /// </remarks>
        public string Summary { get; set; }

        /// <remarks>
        /// Has a max length of 4000. Is not indexed and *IS* used for searches, but is maintained via Lucene. Db column is nvarchar(max).
        /// </remarks>
        public string Tags { get; set; }

        [StringLength(256)]
        public string Title { get; set; }

        [StringLength(64), Required]
        public string Version { get; set; }

        public bool Listed { get; set; }
        public bool IsPrerelease { get; set; }
        public virtual ICollection<PackageFramework> SupportedFrameworks { get; set; }

        // TODO: it would be nice if we could change the feed so that we don't need to flatten authors and dependencies
        public string FlattenedAuthors { get; set; }
        public string FlattenedDependencies { get; set; }
    }
}

nugetgallery/Website/Entities/User.cs
using System;
using System.Collections.Generic;

namespace NuGetGallery
{
    public class User : IEntity
    {
        public User()
            : this(null, null)
        {
        }

        public User(
            string username,
            string hashedPassword)
        {
            HashedPassword = hashedPassword;
            Messages = new HashSet<EmailMessage>();
            Username = username;
        }

        public int Key { get; set; }

        public Guid ApiKey { get; set; }
        public string EmailAddress { get; set; }
        public string UnconfirmedEmailAddress { get; set; }
        public string HashedPassword { get; set; }
        public string PasswordHashAlgorithm { get; set; }
        public virtual ICollection<EmailMessage> Messages { get; set; }
        public string Username { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public bool EmailAllowed { get; set; }
        public bool Confirmed
        {
            get
            {
                return !String.IsNullOrEmpty(EmailAddress);
            }
        }
        public string EmailConfirmationToken { get; set; }
        public string PasswordResetToken { get; set; }
        public DateTime? PasswordResetTokenExpirationDate { get; set; }

        public void ConfirmEmailAddress()
        {
            if (String.IsNullOrEmpty(UnconfirmedEmailAddress))
            {
                throw new InvalidOperationException("User does not have an email address to confirm");
            }
            EmailAddress = UnconfirmedEmailAddress;
            EmailConfirmationToken = null;
            UnconfirmedEmailAddress = null;
        }
    }
}

nugetgallery/Website/ViewModels/AccountViewModel.cs
using System.Collections.Generic;

namespace NuGetGallery
{
    public class AccountViewModel
    {
        public string UserName { get; set; }
        public string ApiKey { get; set; }
        public IEnumerable<string> CuratedFeeds { get; set; } 
    }
}

nugetgallery/Website/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Net.Mail;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;

namespace NuGetGallery
{
    public partial class UsersController : AppController
    {
        readonly IUserService userService;
        readonly IPackageService packageService;
        readonly IMessageService messageService;
        readonly GallerySetting settings;
        readonly IPrincipal currentUser;

        public UsersController(
            IUserService userSvc,
            IPackageService packageService,
            IMessageService messageService,
            GallerySetting settings,
            IPrincipal currentUser)
        {
            this.userService = userSvc;
            this.packageService = packageService;
            this.messageService = messageService;
            this.settings = settings;
            this.currentUser = currentUser;
        }

        [Authorize]
        public virtual ActionResult Account()
        {
            var user = GetService<IUserByUsernameQuery>().Execute(Identity.Name);
            var curatedFeeds = GetService<ICuratedFeedsByManagerQuery>().Execute(user.Key);
            return View(new AccountViewModel
            {
                ApiKey = user.ApiKey.ToString(),
                CuratedFeeds = curatedFeeds.Select(cf => cf.Name),
            });
        }

        [Authorize]
        public virtual ActionResult Edit()
        {
            var user = userService.FindByUsername(currentUser.Identity.Name);
            var model = new EditProfileViewModel
            {
                EmailAddress = user.EmailAddress,
                EmailAllowed = user.EmailAllowed,
                PendingNewEmailAddress = user.UnconfirmedEmailAddress
            };
            return View(model);
        }

        [Authorize, HttpPost, ValidateAntiForgeryToken]
        public virtual ActionResult Edit(EditProfileViewModel profile)
        {
            if (ModelState.IsValid)
            {
                var user = userService.FindByUsername(currentUser.Identity.Name);
                if (user == null)
                {
                    return HttpNotFound();
                }

                string existingConfirmationToken = user.EmailConfirmationToken;
                try
                {
                    userService.UpdateProfile(user, profile.EmailAddress, profile.EmailAllowed);
                }
                catch (EntityException ex)
                {
                    ModelState.AddModelError(String.Empty, ex.Message);
                    return View(profile);
                }

                if (existingConfirmationToken == user.EmailConfirmationToken)
                {
                    TempData["Message"] = "Account settings saved!";
                }
                else
                {
                    TempData["Message"] = "Account settings saved! We sent a confirmation email to verify your new email. When you confirm the email address, it will take effect and we will forget the old one.";

                    var confirmationUrl = Url.ConfirmationUrl(MVC.Users.Confirm(), user.Username, user.EmailConfirmationToken, protocol: Request.Url.Scheme);
                    messageService.SendEmailChangeConfirmationNotice(new MailAddress(profile.EmailAddress, user.Username), confirmationUrl);
                }

                return RedirectToAction(MVC.Users.Account());
            }
            return View(profile);
        }

        public virtual ActionResult Register()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public virtual ActionResult Register(RegisterRequest request)
        {
            // TODO: consider client-side validation for unique username
            // TODO: add email validation

            if (!ModelState.IsValid)
                return View();

            User user;
            try
            {
                user = userService.Create(
                    request.Username,
                    request.Password,
                    request.EmailAddress);
            }
            catch (EntityException ex)
            {
                ModelState.AddModelError(String.Empty, ex.Message);
                return View();
            }

            if (settings.ConfirmEmailAddresses)
            {
                // Passing in scheme to force fully qualified URL
                var confirmationUrl = Url.ConfirmationUrl(MVC.Users.Confirm(), user.Username, user.EmailConfirmationToken, protocol: Request.Url.Scheme);
                messageService.SendNewAccountEmail(new MailAddress(request.EmailAddress, user.Username), confirmationUrl);
            }
            return RedirectToAction(MVC.Users.Thanks());
        }

        public virtual ActionResult Thanks()
        {
            if (settings.ConfirmEmailAddresses)
            {
                return View();
            }
            else
            {
                var model = new EmailConfirmationModel { SuccessfulConfirmation = true, ConfirmingNewAccount = true };
                return View("Confirm", model);
            }
        }

        [Authorize]
        public virtual ActionResult Packages()
        {
            var user = userService.FindByUsername(currentUser.Identity.Name);
            var packages = packageService.FindPackagesByOwner(user);

            var published = from p in packages
                            group p by p.PackageRegistration.Id;

            var model = new ManagePackagesViewModel
            {
                Packages = from pr in published
                           select new PackageViewModel(pr.First())
                           {
                               DownloadCount = pr.Sum(p => p.DownloadCount),
                               Version = null
                           },
            };
            return View(model);
        }

        [Authorize, ValidateAntiForgeryToken, HttpPost]
        public virtual ActionResult GenerateApiKey()
        {
            userService.GenerateApiKey(currentUser.Identity.Name);
            return RedirectToAction(MVC.Users.Account());
        }

        public virtual ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public virtual ActionResult ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = userService.GeneratePasswordResetToken(model.Email, Constants.DefaultPasswordResetTokenExpirationHours * 60);
                if (user != null)
                {
                    var resetPasswordUrl = Url.ConfirmationUrl(MVC.Users.ResetPassword(), user.Username, user.PasswordResetToken, protocol: Request.Url.Scheme);
                    messageService.SendPasswordResetInstructions(user, resetPasswordUrl);

                    TempData["Email"] = user.EmailAddress;
                    return RedirectToAction(MVC.Users.PasswordSent());
                }

                ModelState.AddModelError("Email", "Could not find anyone with that email.");
            }

            return View(model);
        }

        public virtual ActionResult ResendConfirmation()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public virtual ActionResult ResendConfirmation(ResendConfirmationEmailViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = userService.FindByUnconfimedEmailAddress(model.Email);
                if (user != null && !user.Confirmed)
                {
                    var confirmationUrl = Url.ConfirmationUrl(MVC.Users.Confirm(), user.Username, user.EmailConfirmationToken, protocol: Request.Url.Scheme);
                    messageService.SendNewAccountEmail(new MailAddress(user.UnconfirmedEmailAddress, user.Username), confirmationUrl);
                    return RedirectToAction(MVC.Users.Thanks());
                }
                ModelState.AddModelError("Email", "There was an issue resending your confirmation token.");
            }
            return View(model);
        }

        public virtual ActionResult PasswordSent()
        {
            ViewBag.Email = TempData["Email"];
            ViewBag.Expiration = Constants.DefaultPasswordResetTokenExpirationHours;
            return View();
        }

        public virtual ActionResult ResetPassword()
        {
            ViewBag.ResetTokenValid = true;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public virtual ActionResult ResetPassword(string username, string token, PasswordResetViewModel model)
        {
            ViewBag.ResetTokenValid = userService.ResetPasswordWithToken(username, token, model.NewPassword);

            if (!ViewBag.ResetTokenValid)
            {
                ModelState.AddModelError("", "The Password Reset Token is not valid or expired.");
                return View(model);
            }
            return RedirectToAction(MVC.Users.PasswordChanged());
        }

        public virtual ActionResult Confirm(string username, string token)
        {
            if (String.IsNullOrEmpty(token))
            {
                return HttpNotFound();
            }
            var user = userService.FindByUsername(username);
            if (user == null)
            {
                return HttpNotFound();
            }

            string existingEmail = user.EmailAddress;
            var model = new EmailConfirmationModel
            {
                ConfirmingNewAccount = String.IsNullOrEmpty(existingEmail),
                SuccessfulConfirmation = userService.ConfirmEmailAddress(user, token)
            };

            if (!model.ConfirmingNewAccount)
            {
                messageService.SendEmailChangeNoticeToPreviousEmailAddress(user, existingEmail);
            }
            return View(model);

nugetgallery/Website/Views/Users/Account.cshtml
@model AccountViewModel
@{
    ViewBag.Tab = "Contribute";
}

<h1 class="page-heading">My Account</h1>

<section id="actions">
    <h1>Actions</h1>
    <ul>
        <li id="uploadPackage">
            <h2><a href="@Url.UploadPackage()">Upload Package</a></h2>
            <p>
                Upload and publish your package for other NuGet users to download and enjoy. 
                You can upload multiple revisions of the same package, as long as the version 
                is different.
            </p>
        </li>
        @if (Model.CuratedFeeds.Any())
        {
        <li id="manageCuratedFeeds">
            <h2>Manage My Curated Feeds</h2>
            <p>Click a curated feed to manage the included packages.</p>
            <ul>
            @foreach(var curatedFeed in Model.CuratedFeeds)
            {
                <li><a href="@Url.RouteUrl(RouteName.CuratedFeed, new { name = curatedFeed })">@curatedFeed</a></li>
            }
            </ul>
        </li>
        }
        <li id="managePackages">
            <h2><a href="@Url.Action(MVC.Users.Packages())">Manage My Packages</a></h2>
            <p>Edit package details or Remove packages that you have previously uploaded.</p>
        </li>
        <li id="editProfile">
            <h2><a href="@Url.Action(MVC.Users.Edit())">Edit Profile</a></h2>
            <p>Edit your public profile.</p>
        </li>
        <li id="changePassword">
            <h2><a href="@Url.Action(MVC.Users.ChangePassword())">Change Password</a></h2>
            <p>Change your password.</p>
        </li>
    </ul>
</section>



<section id="apiKey">
<h1>API Key</h1>
    <p>
        Your API key provides you with a token that identifies you to the gallery. 
        Keep this a secret. You can always regenerate your key at any time (invalidating 
        previous keys) if your token is accidentally revealed. The 
        <a href="http://nuget.codeplex.com/">NuGet</a> command-line utility allows you to 
        submit a NuGet package to the gallery. 
    </p>
    <p>
        You can install the nuget command-line utility using chocolatey like so:
        <pre>
cinst nuget.commandline
        </pre>
        and you would pass your token like this:
    </p>
    
    <div id="generateKey">
        <h2>Your API key is:</h2>
        
        <div>
            <p>
                <span id="key">@Model.ApiKey</span>
                <img id="copyButton" alt="Copy To Clipboard" src="@Url.Content("~/Content/Images/copy.png")" />
            </p>
            

            <fieldset class="form">
                <legend>Generate New API Key</legend>
                @using (Html.BeginForm("GenerateApiKey", "Users", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Generate New API Key" />
                }
            </fieldset>

            <h2>Example usage:</h2>
            <p>
                <pre>
nuget setApiKey @Model.ApiKey
nuget push MyPackage.1.0.nupkg</pre>
            </p>
        </div>

        <div id="overlayWrapper" title="Click to show API Key">
            Your key is hidden for privacy, click to show.
        </div>
    </div>
</section>

@section BottomScripts {
    <script type="text/javascript" src="@Url.Content("~/Scripts/ZeroClipboard.js")"></script>
    <script>
        $(function () {
            $("#overlayWrapper").click(function () {
                $("#overlayWrapper").fadeOut();
                return false;
            });

            ZeroClipboard.setMoviePath('@Url.Content("~/Scripts/ZeroClipboard.swf")');
            var clip = new ZeroClipboard.Client();
            clip.setText('@HttpUtility.JavaScriptStringEncode(Model.ApiKey.ToString())');
            clip.setHandCursor(true);
            clip.glue('copyButton');
        });
    </script>
}

nugetgallery/Website/Views/Users/ChangePassword.cshtml
@model PasswordChangeViewModel
@{
    ViewBag.Title = "Change Password";
}
             
<h1 class="page-heading">Change Password</h1>

@using (Html.BeginForm()) {
    <fieldset class="form">
        <legend>Register Form</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
              
        @Html.EditorForModel()

        <img src="@Url.Content("~/content/images/required.png")" alt="Blue border on left means required." />

        <input type="submit" value="Save" title="Change password" />
        <a class="cancel" href="@Url.Action("Account")" title="Cancel Changes and go back.">Cancel</a>
    </fieldset>
}

@section BottomScripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}

nugetgallery/Website/Views/Users/Confirm.cshtml
@model EmailConfirmationModel

<h1 class="page-heading">Confirm Registration</h1>

@if (Model.SuccessfulConfirmation) {
    <p>
        @if (Model.ConfirmingNewAccount) {
            @: Account registration completed!
        }
        else {
            @: Email address change confirmed!
        }
    </p>
    if (Model.ConfirmingNewAccount) {
        <p>
            Click on the Log On link to logon to the site.
        </p>
        <p>
            You may now upload packages and make your mark in 
            the community.
        </p>
    }
    else {
        <p>
            Your email address is now updated.
        </p>
    }
}

 else {
    <p class="message error">
        Could not confirm your email address.
    </p>
    <p>
        Make sure you clicked on the confirmation URL in the email we sent.
    </p>
}

nugetgallery/Website/Views/Users/Edit.cshtml
@model EditProfileViewModel
@{
    ViewBag.Title = "Edit Profile";
}


<h1 class="page-heading">Edit Profile</h1>

@Html.ValidationSummary(true)

@if (!String.IsNullOrEmpty(Model.PendingNewEmailAddress)) {
    <p class="message">
        You recently requested to change your email address to <strong>@Model.PendingNewEmailAddress</strong>. 
        This change will take effect when you confirm the address. Check your inbox (or spam folder) for an 
        email with a confirmation link.
    </p>
}

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <fieldset class="form">
        <legend>Edit Profile</legend>

        <div class="form-field">
            @Html.LabelFor(m => m.EmailAddress)
            @Html.EditorFor(m => m.EmailAddress)
            @Html.ValidationMessageFor(m => m.EmailAddress)
            <span class="field-hint-message">If you change your email address, you will need to confirm 
                your new address for it to take effect.</span>
        </div>

        <div class="form-field">
            @Html.EditorFor(m => m.EmailAllowed)
            <label for="EmailAllowed" class="checkbox">
                Receive Email Notifications 
            </label>
            <p>
                <strong>Important:</strong> This setting allows other <em>registered</em> users of the site to contact you 
                about packages that you own using the <em>Contact Maintainers</em> form, or to request that you become a maintainer 
                of their package. Unchecking this means users cannot contact you for these reasons.
            </p>

        </div>

        <img src="@Url.Content("~/content/images/required.png")" alt="Blue border on left means required." />

        <input type="submit" value="Save" title="Save Changes" />
        <a class="cancel" href="@Url.Action("Account")" title="Cancel Changes and go back.">Cancel</a>
    </fieldset>
}

@section BottomScripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}

nugetgallery/Website/Views/Users/ForgotPassword.cshtml
@model ForgotPasswordViewModel
@{
    ViewBag.Title = "Forgot Password";
}

<h1 class="page-heading">Forgot Password</h1>

<p>
    We are sorry to hear you forgot your password. Enter your email below and we will 
    send instructions to reset your password.
</p>

@using (Html.BeginForm()) {
    <fieldset class="form">
        <legend>Register Form</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
              
        @Html.EditorForModel()

        <img src="@Url.Content("~/content/images/required.png")" alt="Blue border on left means required." />

        <input type="submit" value="Send" title="Send Instructions" />
        <a class="cancel" href="@Url.LogOn()" title="Cancel Changes and go back.">Cancel</a>
    </fieldset>
}

@section BottomScripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}

nugetgallery/Website/Views/Users/Packages.cshtml
@model ManagePackagesViewModel
@{
    ViewBag.Tab = "Packages";
}

<h1 class="page-heading">Manage My Packages</h1>


@if (Model.Packages.Any()) {
    <section id="published">
        <h1>Packages</h1>
        <p>These packages are currently published for the world to see.</p>

        @PrintPublishedPackages(Model.Packages.Where(p => p.Listed), unlisted: false)
    </section>

    var unlistedPackages = Model.Packages.Where(p => !p.Listed);
    if (unlistedPackages.Any()) {
    <section id="unlisted">
        <h1>Unlisted Packages</h1>
        <p>These packages are currently unlisted.</p>

        @PrintPublishedPackages(unlistedPackages, unlisted: true)
    </section>
    }
}
else {
    <section id="published">
        <h1>No Packages!</h1>
        <p>
            You don't have any packages. Maybe now is a good time to 
            <a href="@Url.UploadPackage()" class="silverButtonBig">upload a package</a>.
        </p>
    </section>
}

@helper PrintPublishedPackages(IEnumerable<PackageViewModel> packages, bool unlisted) {
    var totlalDownloads = 0;
    <table class="sexy-table">
        <thead>
            <tr>
                <th class="first actions">Actions</th>
                <th>Package</th>
                <th>Package ID</th>
                <th>Description</th>
                <th class="last">Downloads</th>
                
            </tr>
        </thead>
        <tbody>
        @foreach (var package in packages) {
            <tr>
                <td class="actions">
                    @if (unlisted)
                    {
                        <a href="@Url.DeletePackage(package)" title="List Package" class="editPackageLink"><img src="@Links.Content.Images.editIcon_png" alt="List Package" /></a>
                    }
                    else
                    { 
                        <a href="@Url.EditPackage(package)" title="Edit" class="editPackageLink"><img src="@Links.Content.Images.editIcon_png" alt="Edit" /></a>
                        <a href="@Url.DeletePackage(package)" title="Delete" class="deletePackageLink"><img src="@Links.Content.Images.trash_png" alt="Delete" /></a>
                    }
                </td>
                <td>
                    <a href="@Url.Package(package)"  title="View package page.">@package.Title</a>
                </td>
                <td>@package.Id</td>
                <td>
                    @if (String.IsNullOrEmpty(package.Description) || package.Description.Length < 65)
                    {
                            @package.Description
                    }
                    else
                    {
                            @package.Description.Substring(0, 65)
                            <a href="@Url.Package(package)" title="View package page.">...</a>
                    }
                </td>
                
                <td>@package.DownloadCount</td>
            </tr>
                    totlalDownloads += package.DownloadCount;
        }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    You have a total of @packages.Count() packages.
                </td>
                <td class="total">
                    @totlalDownloads
                </td>
            </tr>
        </tfoot>
    </table>
}

nugetgallery/Website/Views/Users/PasswordChanged.cshtml
<h1 class="page-heading">Password changed!</h1>


<p class="message">
    Don't forget to use your new password the next time you 
    <a href="@Url.LogOn()">log on</a>. 
</p>

nugetgallery/Website/Views/Users/PasswordSent.cshtml
@{
    ViewBag.Title = "Password Reset";
}


<h1 class="page-heading">Password Reset Sent</h1>


<p>
    We've sent an email 
    @if (!String.IsNullOrEmpty(ViewBag.Email)) {
        @:to @ViewBag.Email
    } 
    else {
        @:to you
    } 
    containing a temporary url that will allow you to reset your password for 
    the next @ViewBag.Expiration hours. 
</p>
<p>
    Please check your spam folder if you don't receive the email within a 
    few minutes.
</p>

nugetgallery/Website/Views/Users/Profiles.cshtml
@using NuGetGallery;
@model UserProfileModel
@{
    ViewBag.Title = @Model.Username;
    Layout = "~/Views/Shared/TwoColumnLayout.cshtml";
}


@section SideColumn {
    @ViewHelpers.GravatarImage(Model.EmailAddress, Model.Username, 128)
     <div id="stats">
        <div class="stat">
            <p class="stat-number">@Model.Packages.Count.ToString("n0")</p>
            <p class="stat-label">Packages</p>
        </div>
        <div class="stat">
            <p class="stat-number">@Model.TotalPackageDownloadCount.ToString("n0")</p>
            <p class="stat-label">Downloads of @Model.Username's packages</p>
        </div>
    </div>
}

<h1>@Model.Username's Profile</h1>

<h2>Packages</h2>
<ul id="searchResults">
    @foreach (var package in Model.Packages) {
    <li>
        <section class="package">
            <div class="side">
                <a href="@Url.Package(package.Id)" title="View more about @package.Title">
                    <img src="@(package.IconUrl ?? Links.Content.Images.packageDefaultIcon_50x50_png)" alt="@package.Id icon" onerror="this.src='@Links.Content.Images.packageDefaultIcon_50x50_png';" />
                </a>
            </div>
            <div class="main">
                <h1><a href="@Url.Package(package.Id)">@package.Title</a></h1>
                
                <p>
                    @if (String.IsNullOrEmpty(package.Description) || package.Description.Length < 350) {
                        @package.Description
                    }
                    else {
                        @package.Description.Substring(0, 350)<text>... </text><a href="@Url.Package(package)">More information</a>
                    }
                </p>

                <footer>
                    <p class="downloads">
                        @package.TotalDownloadCount.ToString("n0") downloads
                    </p>
                </footer>
            </div>
        </section>
    </li>
    }
</ul>